#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
ENV_FILE=${SALAD_PRL_ENV:-"$REPO_ROOT/.env"}
if [[ -f "$ENV_FILE" ]]; then
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ -n "$line" ]] || continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ "$line" == *"="* ]] || continue
    key=${line%%=*}
    value=${line#*=}
    key=${key//[[:space:]]/}
    [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    if [[ -z "${!key+x}" ]]; then
      value=${value%\"}
      value=${value#\"}
      value=${value%\'}
      value=${value#\'}
      export "$key=$value"
    fi
  done < "$ENV_FILE"
fi
STATE_DIR=${SALAD_PRL_STATE_DIR:-"$REPO_ROOT/state"}
LOG_DIR="$STATE_DIR/logs"
mkdir -p "$LOG_DIR"
STOPPED_SLOT_STATE_PATH=${PRL_STOPPED_SLOT_STATE_PATH:-"$STATE_DIR/prl_stopped_slots.json"}

SCRIPT="$SCRIPT_DIR/salad_prl_watch.py"
GUARD="$SCRIPT_DIR/salad_prl_guard.py"
PREFLIGHT="$SCRIPT_DIR/salad_prl_preflight.py"
PYTHON=${SALAD_PRL_PYTHON:-"$REPO_ROOT/.venv/bin/python"}
if [[ ! -x "$PYTHON" ]]; then
  PYTHON=python3
fi
KRY1_ORG_ID=kry1
COMMON_ORGS=${PRL_FLEET_ORGS:-kray,kry1,kray2,kray3}
DEFAULT_API_KEY_ENV=${PRL_WATCH_DEFAULT_API_KEY_ENV:-SALAD_API_KEY}
FLEET_MODE=${PRL_FLEET_MODE:-fill}
AGGRESSIVE_DISCOVERY=${PRL_AGGRESSIVE_DISCOVERY:-1}
TARGET_OFFSET=${PRL_WATCH_TARGET_OFFSET:-0}
ALLOWED_PRIORITIES=${PRL_WATCH_ALLOWED_PRIORITIES:-batch,low}
BLOCKED_PROFILES=${PRL_WATCH_BLOCKED_PROFILES:-5070:low,5090:low}
COORDINATED_TARGET_OFFSETS=${PRL_WATCH_COORDINATED_TARGET_OFFSETS:-1}
if [[ "$AGGRESSIVE_DISCOVERY" =~ ^(1|true|yes)$ ]]; then
  POLL_SECONDS=${PRL_POLL_SECONDS:-15}
  ALLOCATING_ROTATE_SECONDS=${PRL_ALLOCATING_ROTATE_SECONDS:-900}
  STOPPED_RESTART_COOLDOWN_SECONDS=${PRL_STOPPED_RESTART_COOLDOWN_SECONDS:-60}
  EMPTY_STUCK_NON_LIVE_SECONDS=${PRL_EMPTY_STUCK_NON_LIVE_SECONDS:-3600}
  NO_GPU_SLEEP_AFTER_SECONDS=${PRL_NO_GPU_SLEEP_AFTER_SECONDS:-0}
  NO_GPU_SLEEP_SECONDS=${PRL_NO_GPU_SLEEP_SECONDS:-0}
  ZERO_AVAILABLE_PROBE_BUDGET=${PRL_WATCH_ZERO_AVAILABLE_PROBE_BUDGET:-10}
  ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS=${PRL_WATCH_ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS:-30}
  STUCK_NON_LIVE_MAX_ACTIONS=${PRL_STUCK_NON_LIVE_MAX_ACTIONS:-1}
else
  POLL_SECONDS=${PRL_POLL_SECONDS:-30}
  ALLOCATING_ROTATE_SECONDS=${PRL_ALLOCATING_ROTATE_SECONDS:-900}
  STOPPED_RESTART_COOLDOWN_SECONDS=${PRL_STOPPED_RESTART_COOLDOWN_SECONDS:-120}
  EMPTY_STUCK_NON_LIVE_SECONDS=${PRL_EMPTY_STUCK_NON_LIVE_SECONDS:-3600}
  NO_GPU_SLEEP_AFTER_SECONDS=${PRL_NO_GPU_SLEEP_AFTER_SECONDS:-300}
  NO_GPU_SLEEP_SECONDS=${PRL_NO_GPU_SLEEP_SECONDS:-120}
  ZERO_AVAILABLE_PROBE_BUDGET=${PRL_WATCH_ZERO_AVAILABLE_PROBE_BUDGET:-0}
  ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS=${PRL_WATCH_ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS:-0}
  STUCK_NON_LIVE_MAX_ACTIONS=${PRL_STUCK_NON_LIVE_MAX_ACTIONS:-1}
fi
STUCK_NON_LIVE_MIN_ACTIVE_SLOTS=${PRL_STUCK_NON_LIVE_MIN_ACTIVE_SLOTS:-28}
HTTP_TIMEOUT_SECONDS=15
SNAPSHOT_HTTP_TIMEOUT_SECONDS=${PRL_SNAPSHOT_HTTP_TIMEOUT_SECONDS:-8}
SNAPSHOT_HTTP_ATTEMPTS=${PRL_SNAPSHOT_HTTP_ATTEMPTS:-3}
NOHASH_GRACE_SECONDS=${PRL_NOHASH_GRACE_SECONDS:-900}
STALE_WORKER_GRACE_SECONDS=${PRL_STALE_WORKER_GRACE_SECONDS:-900}
UNDERPERFORM_GRACE_SECONDS=120
UNDERPERFORM_RATIO=0.85
UNDERPERFORM_MIN_DEFICIT_TH=10
STUCK_NON_LIVE_TICK_BUDGET_SECONDS=${PRL_STUCK_NON_LIVE_TICK_BUDGET_SECONDS:-20}
STUCK_NON_LIVE_SECONDS=${PRL_STUCK_NON_LIVE_SECONDS:-3600}
STUCK_RUNNING_ZERO_DEFER_SECONDS=${PRL_STUCK_RUNNING_ZERO_DEFER_SECONDS:-3600}
GLOBAL_POOL_MIN_FRESH_WORKERS=${PRL_GLOBAL_POOL_MIN_FRESH_WORKERS:-8}
ORG_COUNT=0
IFS=',' read -ra COUNT_ORGS <<< "$COMMON_ORGS"
for org in "${COUNT_ORGS[@]}"; do
  org=${org//[[:space:]]/}
  [[ -n "$org" ]] && ORG_COUNT=$((ORG_COUNT + 1))
done
LIVE_UPGRADE_GLOBAL_MIN_FRESH_WORKERS=${PRL_LIVE_UPGRADE_GLOBAL_MIN_FRESH_WORKERS:-$((ORG_COUNT * 10 - 3))}
if (( LIVE_UPGRADE_GLOBAL_MIN_FRESH_WORKERS < 0 )); then
  LIVE_UPGRADE_GLOBAL_MIN_FRESH_WORKERS=0
fi
PROFILE_MISMATCH_GRACE_SECONDS=120
ALLOCATING_RETARGET_AVAILABLE_SECONDS=${PRL_ALLOCATING_RETARGET_AVAILABLE_SECONDS:-180}
LOW_LIVE_MIN_LIVE_WORKERS=${PRL_LOW_LIVE_MIN_LIVE_WORKERS:-8}
LOW_LIVE_ALLOCATING_RETARGET_AVAILABLE_SECONDS=${PRL_LOW_LIVE_ALLOCATING_RETARGET_AVAILABLE_SECONDS:-$ALLOCATING_ROTATE_SECONDS}
CREATE_PROGRESS_SECONDS=900
EMPTY_CREATING_SECONDS=600
UPGRADE_TO_BEST_SECONDS=999999
LIVE_UPGRADE_INTERVAL_SECONDS=${PRL_LIVE_UPGRADE_INTERVAL_SECONDS:-10800}
LIVE_UPGRADE_MIN_PROFIT_DAY=${PRL_LIVE_UPGRADE_MIN_PROFIT_USD_DAY:-0.5}
LIVE_UPGRADE_MIN_TH_DELTA=${PRL_LIVE_UPGRADE_MIN_TH_DELTA:-40}
LIVE_UPGRADE_MIN_LIVE_WORKERS=${PRL_LIVE_UPGRADE_MIN_LIVE_WORKERS:-9}
LIVE_UPGRADE_REQUIRE_FULL_SLOTS=${PRL_LIVE_UPGRADE_REQUIRE_FULL_SLOTS:-1}
LIVE_UPGRADE_REQUIRE_REPORTED_AVAILABLE=${PRL_LIVE_UPGRADE_REQUIRE_REPORTED_AVAILABLE:-1}
NO_CREDITS_BACKOFF_SECONDS=${PRL_NO_CREDITS_BACKOFF_SECONDS:-120}
NO_CREDITS_TARGET_REFRESH_SECONDS=${PRL_NO_CREDITS_TARGET_REFRESH_SECONDS:-300}
GUARD_POLL_SECONDS=${PRL_GUARD_POLL_SECONDS:-20}
NEGATIVE_SLOT_GRACE_SECONDS=${PRL_NEGATIVE_SLOT_GRACE_SECONDS:-900}
ORG_BALANCE_MAX_AGE_SECONDS=10800
FILL_FIXED_DECISION_PRICE_USD=${PRL_FILL_FIXED_DECISION_PRICE_USD:-0.64}
OPTIMIZE_FIXED_DECISION_PRICE_USD=${PRL_OPTIMIZE_FIXED_DECISION_PRICE_USD:-0.62}
FILL_MIN_PROFIT_DAY=${PRL_FILL_MIN_PROFIT_USD_DAY:-0.05}
OPTIMIZE_MIN_PROFIT_DAY=${PRL_OPTIMIZE_MIN_PROFIT_USD_DAY:-0.01}
MINER_RELEASE_TAG=v.1.1.8
MINER_PACKAGE_VERSION=v1.1.8
MINER_BINARY=miner-cuda12

case "$FLEET_MODE" in
  fill)
    FIXED_DECISION_PRICE_USD=$FILL_FIXED_DECISION_PRICE_USD
    MIN_PROFIT_DAY=$FILL_MIN_PROFIT_DAY
    NEGATIVE_SLOT_PROFIT_DAY=0
    UNDERPERFORM_GRACE_SECONDS=999999
    LIVE_UPGRADE_SECONDS=${PRL_FILL_LIVE_UPGRADE_SECONDS:-1800}
    ;;
  optimize)
    FIXED_DECISION_PRICE_USD=$OPTIMIZE_FIXED_DECISION_PRICE_USD
    MIN_PROFIT_DAY=$OPTIMIZE_MIN_PROFIT_DAY
    NEGATIVE_SLOT_PROFIT_DAY=0.01
    UNDERPERFORM_GRACE_SECONDS=120
    LIVE_UPGRADE_SECONDS=${PRL_OPTIMIZE_LIVE_UPGRADE_SECONDS:-300}
    ;;
  *)
    echo "unknown PRL_FLEET_MODE: $FLEET_MODE" >&2
    exit 2
    ;;
esac
DECISION_PRICE_CAP_USD=$FIXED_DECISION_PRICE_USD
if [[ "$FIXED_DECISION_PRICE_USD" == "0" || "$FIXED_DECISION_PRICE_USD" == "0.0" || "$FIXED_DECISION_PRICE_USD" == "0.00" ]]; then
  DECISION_PRICE_CAP_USD=${PRL_DECISION_PRICE_CAP_USD:-0}
fi
FALLBACK_DECISION_PRICE_USD=${PRL_NOHASH_FALLBACK_PRICE:-0.62}
if [[ "$FIXED_DECISION_PRICE_USD" != "0" && "$FIXED_DECISION_PRICE_USD" != "0.0" && "$FIXED_DECISION_PRICE_USD" != "0.00" ]]; then
  FALLBACK_DECISION_PRICE_USD=$FIXED_DECISION_PRICE_USD
fi

"$PYTHON" "$PREFLIGHT" --decision-price "$FIXED_DECISION_PRICE_USD" --min-profitable-profiles 1

slots() {
  local prefix=$1
  local out=""
  local i
  for i in $(seq -w 1 10); do
    if [[ -n "$out" ]]; then
      out+=","
    fi
    out+="${prefix}-${i}"
  done
  printf '%s' "$out"
}

api_key_env_for_org() {
  local org=$1
  local key_env=$DEFAULT_API_KEY_ENV
  local upper_org
  local per_org_var
  upper_org=$(printf '%s' "$org" | tr '[:lower:]-' '[:upper:]_')
  per_org_var="PRL_WATCH_API_KEY_ENV_${upper_org}"
  if [[ -n "${!per_org_var+x}" && -n "${!per_org_var}" ]]; then
    key_env=${!per_org_var}
  fi
  printf '%s' "$key_env"
}

global_pool_prefixes() {
  local out=""
  local org
  IFS=',' read -ra ORGS <<< "$COMMON_ORGS"
  for org in "${ORGS[@]}"; do
    org=${org//[[:space:]]/}
    [[ -n "$org" ]] || continue
    if [[ -n "$out" ]]; then
      out+=","
    fi
    out+="${org}-prl-${org}"
  done
  printf '%s' "$out"
}

GLOBAL_POOL_WORKER_PREFIXES=${PRL_GLOBAL_POOL_WORKER_PREFIXES:-$(global_pool_prefixes)}

restart_tmux() {
  local session=$1
  shift
  tmux has-session -t "$session" 2>/dev/null && tmux kill-session -t "$session"
  tmux new-session -d -s "$session" "$*"
}

watch_cmd() {
  local watch_name=$1
  local log_path=$2
  local org=$3
  local public_org=$4
  local slot_list=$5
  local pool_prefix=$6
  local worker_prefix=$7
  local worker_slot_prefix=$8
  local display_prefix=$9
  local api_key_env=${10:-SALAD_API_KEY_2}

  printf 'cd %q && env' "$REPO_ROOT"
  printf ' PRL_FLEET_MODE=%q' "$FLEET_MODE"
  printf ' PRL_WATCH_NAME=%q' "$watch_name"
  printf ' PRL_WATCH_LOG=%q' "$log_path"
  printf ' PRL_WATCH_ORG=%q' "$org"
  printf ' PRL_WATCH_PUBLIC_ORG=%q' "$public_org"
  printf ' PRL_WATCH_API_KEY_ENV=%q' "$api_key_env"
  printf ' PRL_WATCH_SLOTS=%q' "$slot_list"
  printf ' PRL_WATCH_POOL_WORKER_PREFIX=%q' "$pool_prefix"
  printf ' PRL_WATCH_WORKER_PREFIX=%q' "$worker_prefix"
  printf ' PRL_WATCH_WORKER_SLOT_PREFIX=%q' "$worker_slot_prefix"
  printf ' PRL_WATCH_DISPLAY_PREFIX=%q' "$display_prefix"
  printf ' KRAY2_PRL_POLL_SECONDS=%q' "$POLL_SECONDS"
  printf ' KRAY2_PRL_TRY_SECONDS=%q' "$ALLOCATING_ROTATE_SECONDS"
  printf ' KRAY2_PRL_PROFILE_MISMATCH_GRACE_SECONDS=%q' "$PROFILE_MISMATCH_GRACE_SECONDS"
  printf ' KRAY2_PRL_ALLOCATING_RETARGET_AVAILABLE_SECONDS=%q' "$ALLOCATING_RETARGET_AVAILABLE_SECONDS"
  printf ' KRAY2_PRL_LOW_LIVE_MIN_LIVE_WORKERS=%q' "$LOW_LIVE_MIN_LIVE_WORKERS"
  printf ' KRAY2_PRL_LOW_LIVE_ALLOCATING_RETARGET_AVAILABLE_SECONDS=%q' "$LOW_LIVE_ALLOCATING_RETARGET_AVAILABLE_SECONDS"
  printf ' KRAY2_PRL_STOPPED_RESTART_COOLDOWN_SECONDS=%q' "$STOPPED_RESTART_COOLDOWN_SECONDS"
  printf ' PRL_STOPPED_SLOT_STATE_PATH=%q' "$STOPPED_SLOT_STATE_PATH"
  printf ' KRAY2_PRL_CREATE_PROGRESS_SECONDS=%q' "$CREATE_PROGRESS_SECONDS"
  printf ' KRAY2_PRL_EMPTY_CREATING_SECONDS=%q' "$EMPTY_CREATING_SECONDS"
  printf ' KRAY2_PRL_RUNNING_WITHOUT_POOL_SECONDS=%q' "$NOHASH_GRACE_SECONDS"
  printf ' KRAY2_PRL_UPGRADE_TO_BEST_SECONDS=%q' "$UPGRADE_TO_BEST_SECONDS"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_SECONDS=%q' "$LIVE_UPGRADE_SECONDS"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_INTERVAL_SECONDS=%q' "$LIVE_UPGRADE_INTERVAL_SECONDS"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_MIN_PROFIT_DELTA=%q' "$LIVE_UPGRADE_MIN_PROFIT_DAY"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_MIN_TH_DELTA=%q' "$LIVE_UPGRADE_MIN_TH_DELTA"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_MIN_LIVE_WORKERS=%q' "$LIVE_UPGRADE_MIN_LIVE_WORKERS"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_GLOBAL_MIN_FRESH_WORKERS=%q' "$LIVE_UPGRADE_GLOBAL_MIN_FRESH_WORKERS"
  printf ' PRL_WATCH_GLOBAL_POOL_WORKER_PREFIXES=%q' "$GLOBAL_POOL_WORKER_PREFIXES"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_REQUIRE_FULL_SLOTS=%q' "$LIVE_UPGRADE_REQUIRE_FULL_SLOTS"
  printf ' KRAY2_PRL_OPTIMIZE_LIVE_REQUIRE_REPORTED_AVAILABLE=%q' "$LIVE_UPGRADE_REQUIRE_REPORTED_AVAILABLE"
  printf ' KRAY2_PRL_NO_CREDITS_BACKOFF_SECONDS=%q' "$NO_CREDITS_BACKOFF_SECONDS"
  printf ' PRL_WATCH_NO_CREDITS_TARGET_REFRESH_SECONDS=%q' "$NO_CREDITS_TARGET_REFRESH_SECONDS"
  printf ' KRAY2_PRL_NO_GPU_SLEEP_AFTER_SECONDS=%q' "$NO_GPU_SLEEP_AFTER_SECONDS"
  printf ' KRAY2_PRL_NO_GPU_SLEEP_SECONDS=%q' "$NO_GPU_SLEEP_SECONDS"
  printf ' PRL_WATCH_HTTP_TIMEOUT_SECONDS=%q' "$HTTP_TIMEOUT_SECONDS"
  printf ' PRL_WATCH_ORG_BALANCE_MAX_AGE_SECONDS=%q' "$ORG_BALANCE_MAX_AGE_SECONDS"
  printf ' PRL_WATCH_TARGET_OFFSET=%q' "$TARGET_OFFSET"
  printf ' PRL_WATCH_COORDINATED_TARGET_OFFSETS=%q' "$COORDINATED_TARGET_OFFSETS"
  printf ' PRL_WATCH_ALLOWED_PRIORITIES=%q' "$ALLOWED_PRIORITIES"
  printf ' PRL_WATCH_BLOCKED_PROFILES=%q' "$BLOCKED_PROFILES"
  printf ' PRL_WATCH_ZERO_AVAILABLE_PROBE_BUDGET=%q' "$ZERO_AVAILABLE_PROBE_BUDGET"
  printf ' PRL_WATCH_ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS=%q' "$ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS"
  printf ' PRL_WATCH_MIN_PROFIT_USD_DAY=%q' "$MIN_PROFIT_DAY"
  printf ' PRL_WATCH_PRICE_BAND_USD=%q' "0.02"
  printf ' PRL_WATCH_DECISION_PRICE_CAP_USD=%q' "$DECISION_PRICE_CAP_USD"
  printf ' PRL_WATCH_FIXED_DECISION_PRICE_USD=%q' "$FIXED_DECISION_PRICE_USD"
  printf ' PRL_WATCH_MINER_RELEASE_TAG=%q' "$MINER_RELEASE_TAG"
  printf ' PRL_WATCH_MINER_PACKAGE_VERSION=%q' "$MINER_PACKAGE_VERSION"
  printf ' PRL_WATCH_MINER_BINARY=%q' "$MINER_BINARY"
  printf ' PRL_WATCH_COORDINATED_ORGS=%q' "$COMMON_ORGS"
  printf ' %q %q >> %q 2>&1' "$PYTHON" "$SCRIPT" "$log_path"
}

guard_cmd() {
  printf 'cd %q && env' "$REPO_ROOT"
  printf ' PRL_FLEET_MODE=%q' "$FLEET_MODE"
  printf ' PRL_GUARD_ORGS=%q' "$COMMON_ORGS"
  printf ' PRL_PRICE_BAND_USD=%q' "0.02"
  printf ' PRL_DECISION_PRICE_CAP_USD=%q' "$DECISION_PRICE_CAP_USD"
  printf ' PRL_FIXED_DECISION_PRICE_USD=%q' "$FIXED_DECISION_PRICE_USD"
  printf ' PRL_NEGATIVE_SLOT_PROFIT_DAY=%q' "$NEGATIVE_SLOT_PROFIT_DAY"
  printf ' PRL_NEGATIVE_SLOT_GRACE_SECONDS=%q' "$NEGATIVE_SLOT_GRACE_SECONDS"
  printf ' PRL_UNDERPERFORM_GRACE_SECONDS=%q' "$UNDERPERFORM_GRACE_SECONDS"
  printf ' PRL_UNDERPERFORM_RATIO=%q' "$UNDERPERFORM_RATIO"
  printf ' PRL_UNDERPERFORM_MIN_DEFICIT_TH=%q' "$UNDERPERFORM_MIN_DEFICIT_TH"
  printf ' PRL_NOHASH_GRACE_SECONDS=%q' "$NOHASH_GRACE_SECONDS"
  printf ' PRL_NOHASH_FORCE_GRACE_SECONDS=%q' "$NOHASH_GRACE_SECONDS"
  printf ' PRL_NOHASH_NEGATIVE_GRACE_SECONDS=%q' "$NOHASH_GRACE_SECONDS"
  printf ' PRL_NOHASH_POLL_SECONDS=%q' "$GUARD_POLL_SECONDS"
  printf ' PRL_GLOBAL_POOL_MIN_FRESH_WORKERS=%q' "$GLOBAL_POOL_MIN_FRESH_WORKERS"
  printf ' PRL_STALE_WORKER_GRACE_SECONDS=%q' "$STALE_WORKER_GRACE_SECONDS"
  printf ' PRL_NOHASH_FALLBACK_PRICE=%q' "$FALLBACK_DECISION_PRICE_USD"
  printf ' PRL_STUCK_NON_LIVE_SECONDS=%q' "$STUCK_NON_LIVE_SECONDS"
  printf ' PRL_EMPTY_STUCK_NON_LIVE_SECONDS=%q' "$EMPTY_STUCK_NON_LIVE_SECONDS"
  printf ' PRL_STUCK_NON_LIVE_MAX_ACTIONS=%q' "$STUCK_NON_LIVE_MAX_ACTIONS"
  printf ' PRL_STUCK_NON_LIVE_MIN_ACTIVE_SLOTS=%q' "$STUCK_NON_LIVE_MIN_ACTIVE_SLOTS"
  printf ' PRL_STUCK_NON_LIVE_TICK_BUDGET_SECONDS=%q' "$STUCK_NON_LIVE_TICK_BUDGET_SECONDS"
  printf ' PRL_STUCK_RUNNING_ZERO_DEFER_SECONDS=%q' "$STUCK_RUNNING_ZERO_DEFER_SECONDS"
  printf ' PRL_STOPPED_SLOT_STATE_PATH=%q' "$STOPPED_SLOT_STATE_PATH"
  printf ' KRAY2_PRL_POLL_SECONDS=%q' "$POLL_SECONDS"
  printf ' KRAY2_PRL_TRY_SECONDS=%q' "$ALLOCATING_ROTATE_SECONDS"
  printf ' PRL_WATCH_HTTP_TIMEOUT_SECONDS=%q' "$HTTP_TIMEOUT_SECONDS"
  printf ' PRL_SNAPSHOT_HTTP_TIMEOUT_SECONDS=%q' "$SNAPSHOT_HTTP_TIMEOUT_SECONDS"
  printf ' PRL_SNAPSHOT_HTTP_ATTEMPTS=%q' "$SNAPSHOT_HTTP_ATTEMPTS"
  printf ' PRL_WATCH_NO_CREDITS_TARGET_REFRESH_SECONDS=%q' "$NO_CREDITS_TARGET_REFRESH_SECONDS"
  printf ' PRL_WATCH_TARGET_OFFSET=%q' "$TARGET_OFFSET"
  printf ' PRL_WATCH_COORDINATED_TARGET_OFFSETS=%q' "$COORDINATED_TARGET_OFFSETS"
  printf ' PRL_WATCH_ALLOWED_PRIORITIES=%q' "$ALLOWED_PRIORITIES"
  printf ' PRL_WATCH_BLOCKED_PROFILES=%q' "$BLOCKED_PROFILES"
  printf ' PRL_WATCH_ZERO_AVAILABLE_PROBE_BUDGET=%q' "$ZERO_AVAILABLE_PROBE_BUDGET"
  printf ' PRL_WATCH_ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS=%q' "$ZERO_AVAILABLE_PROBE_MAX_LIVE_WORKERS"
  printf ' PRL_WATCH_MIN_PROFIT_USD_DAY=%q' "$MIN_PROFIT_DAY"
  printf ' PRL_WATCH_PRICE_BAND_USD=%q' "0.02"
  printf ' PRL_WATCH_DECISION_PRICE_CAP_USD=%q' "$DECISION_PRICE_CAP_USD"
  printf ' PRL_WATCH_FIXED_DECISION_PRICE_USD=%q' "$FIXED_DECISION_PRICE_USD"
  printf ' PRL_WATCH_MINER_RELEASE_TAG=%q' "$MINER_RELEASE_TAG"
  printf ' PRL_WATCH_MINER_PACKAGE_VERSION=%q' "$MINER_PACKAGE_VERSION"
  printf ' PRL_WATCH_MINER_BINARY=%q' "$MINER_BINARY"
  printf ' PRL_WATCH_COORDINATED_ORGS=%q' "$COMMON_ORGS"
  printf ' %q %q >> %q 2>&1' "$PYTHON" "$GUARD" "$LOG_DIR/prl_nohash_guard.log"
}

pkill -f '[s]alad_prl_watch.py' || true
pkill -f '[s]alad_prl_guard.py' || true

if [[ -n "${PRL_FLEET_ORGS:-}" ]]; then
  IFS=',' read -ra ORGS <<< "$COMMON_ORGS"
  for org in "${ORGS[@]}"; do
    org=${org//[[:space:]]/}
    [[ -n "$org" ]] || continue
    session="${org}-prl-watch"
    key_env=$(api_key_env_for_org "$org")
    restart_tmux "$session" "$(watch_cmd "$session" "$LOG_DIR/${org}_prl_watch.log" "$org" "$org" "$(slots "prl-${org}-roi")" "${org}-prl-${org}" "${org}-prl" "${org}-roi-" "PearlFortune ${org^^}" "$key_env")"
  done
else
  restart_tmux kray-prl-watch "$(watch_cmd kray-prl-watch "$LOG_DIR/kray_prl_watch.log" kray kray "$(slots prl-kray-roi)" kray-prl-kray kray-prl kray-roi- "PearlFortune KRAY" SALAD_API_KEY_2)"
  restart_tmux kry1-prl-watch "$(watch_cmd kry1-prl-watch "$LOG_DIR/kry1_prl_watch.log" "$KRY1_ORG_ID" kry1 "$(slots prl-kry1-roi)" kry1-prl-kry1 kry1-prl kry1-roi- "PearlFortune KRY1" SALAD_API_KEY_KRY1)"
  restart_tmux kray2-prl-watch "$(watch_cmd kray2-prl-watch "$LOG_DIR/kray2_prl_watch.log" kray2 kray2 "$(slots prl-kray2-roi)" kray2-prl-kray2 kray2-prl kray2-roi- "PearlFortune KRAY2" SALAD_API_KEY_2)"
  restart_tmux kray3-prl-watch "$(watch_cmd kray3-prl-watch "$LOG_DIR/kray3_prl_watch.log" kray3 kray3 "$(slots prl-kray3-roi)" kray3-prl-kray3 kray3-prl kray3-roi- "PearlFortune KRAY3" SALAD_API_KEY_2)"
fi
restart_tmux kray-prl-guard "$(guard_cmd)"

tmux list-sessions | rg 'prl-(watch|guard)'
